import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/molecules/NavbarComponent";
import { AccessibilityProvider } from "@/context/AccessibilityContext";
import ClientLayout from "@/app/ClientLayout";
import SocialsBarComponent from "@/components/atoms/SocialsBarComponent";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsSans.variable} antialiased`} style={{ "--text-size": "16px" } as React.CSSProperties}>
        <AccessibilityProvider>
          <ClientLayout>
            <NavbarComponent />
            {children}
            <SocialsBarComponent/>
          </ClientLayout>
        </AccessibilityProvider>
      </body>
    </html>
  );
}